server.port: 4396
spring.application.name: ribbonServer
userId: ddd
#自定义
defaultWeapon: a very very very buge Trident
#eureka
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:1111/eureka
#actuator
management.security.enabled: false
#rabbitMQ
spring.rabbitmq:
  host: localhost
  port: 5672
  username: scott
  password: tiger
#bus
#spring.cloud.bus:
#  trace:
#    enabled: true